### ISSUE TITLE
やりたいことリスト

### ISSUE THREAD

**Issue by whoiron** [whoiron/adb#3]
## コンテンツ系

- [ ] ホームの説明文
- [x] Aboutの内容
- [x] discordリンク用ページ `/discord` 
- [ ] キャラクター別ページ `/characters`
    アイドルデータをファイルのすれば情報一覧サイトになるので↓のようなデータを入れたい
    ```yaml
    - id: "松田亜利沙"
      type: "Princess"
      weight: "40"
      birthday: "06-07"
      ...
    ```
- [ ] 声優別ページ `/actors`
- [ ] 楽曲別ページ `/songs`
- [ ] クリエイターページ `/creators`
- [ ] ライブ別ページ `/events`
- [ ] リリース別ページ `/releases`

## 見た目系

- [ ] Tableレイアウトを良くする

## 裏側系

- [ ] head情報追加
- [ ] カスタムドメイン
